### ISSUE TITLE
Invalid parameter java_opts on Class[Graylog2::Web]

### ISSUE THREAD

**Issue by nomoresecrets** [Graylog2/graylog2-puppet#31] opened 2015-09-09 11:17 UTC
I'm trying to set this parameter (enabling https) within my puppet manifest but it keeps telling me "invalid parameter" :(

any suggestions?

my manifest looks like this
```
class { '::graylog2::web':
timezone           => 'Europe/Berlin',
application_secret => 'secret',
java_opts          => '-Dhttps.port=9443 -Dhttps.keyStore=/etc/graylog/web/my.keystore 
-Dhttps.keyStorePassword=password -Dhttp.port=disabled',
}
```

**Comment by joschi** [comment] 2015-09-09 11:54
@nomoresecrets Please post the complete and unabridged version of the error message you get from Puppet.

**Comment by nomoresecrets** [comment] 2015-09-09 11:58
root@graylog ~ # puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter java_opts on Class[Graylog2::Web] at /etc/puppet/manifests/graylog.pp:121 on node graylog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by joschi** [comment] 2015-09-09 12:37
@nomoresecrets Which version of the Puppet module are you using? The `java_opts` parameter has been added in June 2015 and does not exist in any released version yet.

**Comment by nomoresecrets** [comment] 2015-09-09 12:48
├── graylog2-graylog2 (v1.1.1)

I've already reinstalled the module, too.

**Comment by joschi** [comment] 2015-09-09 13:10
As I said, the Puppet module hasn't been released in a version that contains this parameter. You will have to use the `master` branch of this module or wait for the next release.

I'm closing this issue since it's not a bug or a feature request.

**Closed by joschi** 2015-09-09 13:10 UTC
